CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    first_name TEXT,

    last_name TEXT,

    avatar_path TEXT,

    FOREIGN KEY(user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);