CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    folder_id BIGINT,

    name TEXT NOT NULL,

    storage_path TEXT NOT NULL,

    size_bytes BIGINT NOT NULL,

    mime_type TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    FOREIGN KEY (folder_id)
        REFERENCES folders(id)
        ON DELETE CASCADE
);