CREATE TABLE users (

    id INTEGER PRIMARY KEY AUTOINCREMENT,

    email TEXT NOT NULL UNIQUE,
    
    username TEXT NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    is_active INTEGER NOT NULL DEFAULT 1

);